// Code generated by protoc-gen-go. DO NOT EDIT.
// source: football/v1/team.proto

package football

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Team struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortName            string    `protobuf:"bytes,3,opt,name=shortName,proto3" json:"shortName,omitempty"`
	Tla                  string    `protobuf:"bytes,4,opt,name=tla,proto3" json:"tla,omitempty"`
	CrestUrl             string    `protobuf:"bytes,5,opt,name=crestUrl,proto3" json:"crestUrl,omitempty"`
	Founded              int32     `protobuf:"varint,6,opt,name=founded,proto3" json:"founded,omitempty"`
	Venue                string    `protobuf:"bytes,7,opt,name=venue,proto3" json:"venue,omitempty"`
	Squad                []*Player `protobuf:"bytes,8,rep,name=squad,proto3" json:"squad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ef97483cd45e089, []int{0}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Team) GetTla() string {
	if m != nil {
		return m.Tla
	}
	return ""
}

func (m *Team) GetCrestUrl() string {
	if m != nil {
		return m.CrestUrl
	}
	return ""
}

func (m *Team) GetFounded() int32 {
	if m != nil {
		return m.Founded
	}
	return 0
}

func (m *Team) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *Team) GetSquad() []*Player {
	if m != nil {
		return m.Squad
	}
	return nil
}

type TeamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamRequest) Reset()         { *m = TeamRequest{} }
func (m *TeamRequest) String() string { return proto.CompactTextString(m) }
func (*TeamRequest) ProtoMessage()    {}
func (*TeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ef97483cd45e089, []int{1}
}

func (m *TeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamRequest.Unmarshal(m, b)
}
func (m *TeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamRequest.Marshal(b, m, deterministic)
}
func (m *TeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamRequest.Merge(m, src)
}
func (m *TeamRequest) XXX_Size() int {
	return xxx_messageInfo_TeamRequest.Size(m)
}
func (m *TeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamRequest proto.InternalMessageInfo

func (m *TeamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Team)(nil), "football.v1.Team")
	proto.RegisterType((*TeamRequest)(nil), "football.v1.TeamRequest")
}

func init() { proto.RegisterFile("football/v1/team.proto", fileDescriptor_7ef97483cd45e089) }

var fileDescriptor_7ef97483cd45e089 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0xb6, 0xe9, 0x1f, 0x57, 0xfa, 0xf4, 0xc9, 0x20, 0x64, 0x55, 0x0c, 0x55, 0xa7,
	0x32, 0x10, 0x2b, 0x30, 0xb2, 0x31, 0x21, 0x86, 0x0a, 0x05, 0x58, 0xd8, 0x6e, 0xe2, 0x5b, 0x12,
	0xc5, 0xb1, 0x53, 0xc7, 0x8e, 0xd4, 0xc7, 0xe4, 0x8d, 0x50, 0x1c, 0x05, 0x32, 0xb2, 0x9d, 0xf3,
	0xbb, 0xe7, 0x0e, 0xe7, 0x90, 0xab, 0xa3, 0xd6, 0x36, 0x05, 0x29, 0x79, 0x1b, 0x73, 0x8b, 0x50,
	0x45, 0xb5, 0xd1, 0x56, 0xd3, 0xf5, 0xc0, 0xa3, 0x36, 0xde, 0xb0, 0x71, 0xa8, 0x96, 0x70, 0x46,
	0xd3, 0xc7, 0x76, 0x5f, 0x01, 0x99, 0xbd, 0x21, 0x54, 0xf4, 0x1f, 0x99, 0x14, 0x82, 0x05, 0xdb,
	0x60, 0xbf, 0x4a, 0x26, 0x85, 0xa0, 0x94, 0xcc, 0x14, 0x54, 0xc8, 0x26, 0x9e, 0x78, 0x4d, 0xaf,
	0xc9, 0xaa, 0xc9, 0xb5, 0xb1, 0x87, 0xee, 0x30, 0xf5, 0x87, 0x5f, 0x40, 0xff, 0x93, 0xa9, 0x95,
	0xc0, 0x66, 0x9e, 0x77, 0x92, 0x6e, 0xc8, 0x32, 0x33, 0xd8, 0xd8, 0x77, 0x23, 0x59, 0xe8, 0xf1,
	0x8f, 0xa7, 0x8c, 0x2c, 0x8e, 0xda, 0x29, 0x81, 0x82, 0xcd, 0xb7, 0xc1, 0x3e, 0x4c, 0x06, 0x4b,
	0x2f, 0x49, 0xd8, 0xa2, 0x72, 0xc8, 0x16, 0xfe, 0xa5, 0x37, 0xf4, 0x86, 0x84, 0xcd, 0xc9, 0x81,
	0x60, 0xcb, 0xed, 0x74, 0xbf, 0xbe, 0xbb, 0x88, 0x46, 0xfd, 0xa2, 0x17, 0x5f, 0x29, 0xe9, 0x13,
	0xbb, 0x98, 0xac, 0xbb, 0x4a, 0x09, 0x9e, 0x1c, 0x36, 0xf6, 0x2f, 0xcd, 0x1e, 0x9f, 0x3f, 0x9e,
	0x3e, 0x0b, 0x9b, 0xbb, 0x34, 0xca, 0x74, 0xc5, 0x5f, 0xf3, 0x42, 0x59, 0x38, 0x40, 0x09, 0x15,
	0xf0, 0xb3, 0x2b, 0x8b, 0xd4, 0xdd, 0x66, 0x39, 0x28, 0x85, 0x92, 0xa7, 0x90, 0x95, 0xa8, 0x04,
	0x37, 0x75, 0xd6, 0xf0, 0xd1, 0xac, 0x0f, 0x83, 0x4e, 0xe7, 0x7e, 0xd9, 0xfb, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x8d, 0xf4, 0xc8, 0x9a, 0x01, 0x00, 0x00,
}
